function nsta = dp_stations( sta_string )
%
% Sets the DP_SCNL cell string array to a pre-set collection of station
%
% Rod Stewart, 2010-01-25


% test if location string passed as argument, if not, ask for it
if (nargin == 0)
    
    sta_string = input( 'Stations: ', 's' );
    
end

switch sta_string
    case 'MVO.SP.All'
        scnl_string = [ 'MBBY.SHZ.--.--,MBBY.SHN.--.--,MBBY.SHE.--.--,' ...
            'MBFL.SHZ.--.--,' ...
            'MBFR.SHZ.--.--,MBFR.SHN.--.--,MBFR.SHE.--.--,' ...
            'MBGB.SHZ.--.--,MBGB.SHN.--.--,MBGB.SHE.--.--,' ...
            'MBGH.SHZ.--.--,MBGH.SHN.--.--,MBGH.SHE.--.--,' ...
            'MBHA.SHZ.--.--,MBHA.SHN.--.--,MBHA.SHE.--.--,' ...
            'MBLG.SHZ.--.--,MBLG.SHN.--.--,MBLG.SHE.--.--,' ...
            'MBLY.SHZ.--.--,MBLY.SHN.--.--,MBLY.SHE.--.--,' ...
            'MBRY.SHZ.--.--,MBRY.SHN.--.--,MBRY.SHE.--.--,' ...
            'MBWH.SHZ.--.--,MBWH.SHN.--.--,MBWH.SHE.--.--,' ...
            'MBWW.SHZ.--.--,MBWW.SHN.--.--,MBWW.SHE.--.--' ...
            ];
    case 'MVO.All.All'
        scnl_string = [ 'MBBY.BHZ.--.--,MBBY.BHN.--.--,MBBY.BHE.--.--,' ...
            'MBFL.SHZ.--.--,' ...
            'MBFR.BHZ.--.--,MBFR.BHN.--.--,MBFR.BHE.--.--,' ...
            'MBGB.BHZ.--.--,MBGB.BHN.--.--,MBGB.BHE.--.--,' ...
            'MBGH.BHZ.--.--,MBGH.BHN.--.--,MBGH.BHE.--.--,' ...
            'MBHA.BHZ.--.--,MBHA.BHN.--.--,MBHA.BHE.--.--,' ...
            'MBLG.BHZ.--.--,MBLG.BHN.--.--,MBLG.BHE.--.--,' ...
            'MBLY.BHZ.--.--,MBLY.BHN.--.--,MBLY.BHE.--.--,' ...
            'MBRY.BHZ.--.--,MBRY.BHN.--.--,MBRY.BHE.--.--,' ...
            'MBWH.BHZ.--.--,MBWH.BHN.--.--,MBWH.BHE.--.--,' ...
            'MBWW.HHZ.--.--,MBWW.HHN.--.--,MBWW.HHE.--.--' ...
            ];
    case 'MVO.SP.Z'
        scnl_string = [ 'MBBY.SHZ.--.--,' ...
            'MBFL.SHZ.--.--,' ...
            'MBFR.SHZ.--.--,' ...
            'MBGB.SHZ.--.--,' ...
            'MBGH.SHZ.--.--,' ...
            'MBHA.SHZ.--.--,' ...
            'MBLG.SHZ.--.--,' ...
            'MBLY.SHZ.--.--,' ...
            'MBRY.SHZ.--.--,' ...
            'MBWH.SHZ.--.--,' ...
            'MBWW.SHZ.--.--' ...
            ];
    case 'MVO.All.Z'
        scnl_string = [ 'MBBY.BHZ.--.--,' ...
            'MBFL.SHZ.--.--,' ...
            'MBFR.BHZ.--.--,' ...
            'MBGB.BHZ.--.--,' ...
            'MBGH.BHZ.--.--,' ...
            'MBHA.BHZ.--.--,' ...
            'MBLG.BHZ.--.--,' ...
            'MBLY.BHZ.--.--,' ...
            'MBRY.BHZ.--.--,' ...
            'MBWH.BHZ.--.--', ...
            ];
    case 'MBGH.BB.3C'
        scnl_string = 'MBGH.BHZ.MVO.--,MBGH.BHN.MVO.--,MBGH.BHE.MVO.--';
    case 'MBFR.BB.3C'
        scnl_string = 'MBFR.BHZ.MVO.--,MBFR.BHN.MVO.--,MBFR.BHE.MVO.--';
    case 'MBHA.BB.3C'
        scnl_string = 'MBHA.BHZ.MVO.--,MBHA.BHN.MVO.--,MBHA.BHE.MVO.--';
    otherwise
        scnl_string = sta_string;
end

if strcmp( scnl_string, 'All' )
    nsta = 0;
    dp_scnls( '' );
else
    s = regexp( scnl_string, ',', 'split' );

    nsta = length( s );

    dp_scnls( scnl_string );

end

return