function vtStrings = read_string_spreadsheet( setup )
% Reads Excel spreadsheet for VT strings
% R.C. Stewart, 18-Mar-2021

data_file = 'SeismicityDiary.xlsx';
fileSeismicVtstrings = fullfile( setup.DirSeismicData, data_file );

w = warning ('off','all');
try
    VT = readtable( fileSeismicVtstrings, 'Sheet', 'Strings' );
catch
    errID = 'read_string_spreadsheet:CantOpenFile';
    msg = 'Unable to open spreadsheet, maybe it is open already.';
    baseException = MException(errID,msg);
    throw( baseException );
end
warning(w);

vtId = VT.ID;
vtDatimFirst = VT.DateTimeStart_UTC_;
vtDatimLast = VT.DateTimeLastEvent_UTC_;
vtDurationMinutes = VT.Duration_min_;
vtNumSeisan = VT.x_VTsSEISAN;
vtNumLocated = VT.x_VTsLocated;
vtNumTotal = VT.x_VTsTotal;
vtMaxMl = VT.MaxML;
vtSurfaceActivity = VT.SurfaceActivity;
vtWhat = VT.What;
%vtEventFile = cell2mat(VT.EventFile);
%vtHeliPlot = cell2mat(VT.HeliPlot);
%vtMultiPlot = cell2mat(VT.MultiPlot);
%vtSeisanFiles = cell2mat(VT.SEISANFiles);
%vtStaFirst = cell2mat(VT.NearestStation);
%vtStaSecond = cell2mat(VT.NextStation);
%vtStaPicked = cell2mat(VT.PickedStation);
vtEventFile = VT.EventFile;
vtHeliPlot = VT.HeliPlot;
vtMultiPlot = VT.MultiPlot;
vtSeisanFiles = VT.SEISANFiles;
vtStaFirst = VT.NearestStation;
vtStaSecond = VT.NextStation;
vtStaPicked = VT.PickedStation;
vtForm = VT.Form;
%vtRepeatingEvents = cell2mat(VT.RepeatingEvents);
vtRepeatingEvents = VT.RepeatingEvents;
vtPurity = VT.Purity_vrlh_;
%vtChecked = cell2mat(VT.Checked);
vtChecked = VT.Checked;
vtComment = VT.Comment;
vtMSCP = VT.MSCP;
vtMSUH = VT.MSUH;
vtMSS1 = VT.MSS1;
vtMBFR = VT.MBFR;
vtMBLG = VT.MBLG;
vtMBLY = VT.MBLY;
vtMBRY = VT.MBRY;
vtMBBY = VT.MBBY;
vtMBHA = VT.MBHA;
vtMSMX = VT.MSMX;
vtMBGH = VT.MBGH;
vtMBWH = VT.MBWH;
vtMBWW = VT.MBWW;

vtStrings = struct( 'Id', {vtId}, ...
                    'What', {vtWhat}, ...
                    'Checked', {vtChecked}, ...
                    'EventFile', {vtEventFile}, ...
                    'Heliplot', {vtHeliPlot}, ...
                    'Multiplot', {vtMultiPlot}, ...
                    'SeisanFiles', {vtSeisanFiles}, ...
                    'Form', {vtForm}, ...
                    'Purity', {vtPurity}, ...
                    'RepeatingEvents', {vtRepeatingEvents}, ...
                    'DatimFirst', vtDatimFirst, ...
                    'DatimLast', vtDatimLast, ...
                    'Duration', vtDurationMinutes, ...
                    'NumSeisan', vtNumSeisan, ...
                    'NumLocated', vtNumLocated, ...
                    'NumTotal', vtNumTotal, ...
                    'MaxMl', vtMaxMl, ...
                    'SurfaceActivity', {vtSurfaceActivity}, ...
                    'StaFirst', {vtStaFirst}, ...
                    'StaSecond', {vtStaSecond}, ...
                    'StaPicked', {vtStaPicked}, ...
                    'MBBY', {vtMBBY}, ...
                    'MBFR', {vtMBFR}, ...
                    'MBGH', {vtMBGH}, ...
                    'MBHA', {vtMBHA}, ...
                    'MBLG', {vtMBLG}, ...
                    'MBLY', {vtMBLY}, ...
                    'MBRY', {vtMBRY}, ...
                    'MBWH', {vtMBWH}, ...
                    'MBWW', {vtMBWW}, ...
                    'MSCP', {vtMSCP}, ...
                    'MSMX', {vtMSMX}, ...
                    'MSS1', {vtMSS1}, ...
                    'MSUH', {vtMSUH}, ...
                    'Comment', {vtComment} );







