function stations = sta_getnet( network )
%
% Returns stations in a particular network
%
% Rod Stewart, 2009-05-23

switch network
    case 'mvo'
        stations = {    'MBBY', ...
                        'MBFL', ...
                        'MBFR', ...
                        'MBGB', ...
                        'MBGH', ...
                        'MBHA', ...
                        'MBLG', ...
                        'MBLY', ...
                        'MBRY', ...
                        'MBRV', ...
                        'MBWH', ...
                        'MBWW' };
    case 'mvo_near'
        stations = {    'MBBY', ...
                        'MBFL', ...
                        'MBFR', ...
                        'MBGB', ...
                        'MBGH', ...
                        'MBHA', ...
                        'MBLG', ...
                        'MBLY', ...
                        'MBRY', ...
                        'MBWH', ...
                        'MBWW' };
    otherwise
        stations = [];
end

return
        